# Start with a standard RHEL Image Mode image for 9.8
# Make sure you've built your Edge Manager server first and have the config.yaml file in the build directory

FROM quay.io/redhat-user-workloads/jetpack-for-rhel-tenant/rhel-98-bootc:6.2.2_5.14.0-687.42.1_083126143115

# Install git and pip/podman-compose for application builds and containers
RUN  dnf -y install git python3-pip && pip install podman-compose

# Create a default 'redhat' user with the specified password.
# Add it to the 'wheel' group to allow for running sudo commands.
ARG USER_PASSWD
RUN if [ -z "${USER_PASSWD}" ] ; then \
        echo USER_PASSWD is a mandatory build argument && exit 1 ; \
    fi
RUN useradd -m -d /var/home/redhat -G wheel redhat && \
    echo "redhat:${USER_PASSWD}" | chpasswd

RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo && \
    dnf -y install tailscale && \
    systemctl enable tailscaled

RUN dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf -y install python3-pip && pip install podman-compose && \
    dnf -y install flightctl-agent-1.3.0~rc4-1.el9.aarch64 && \
    dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf -y install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service

ADD config.yaml /etc/flightctl/
